export const countryNameToCode = new Map([
  ["united states", "US"],
  ["china", "CN"],
  ["japan", "JP"],
  ["germany", "DE"],
  ["united kingdom", "GB"],
  ["india", "IN"],
  ["france", "FR"],
  ["italy", "IT"],
  ["canada", "CA"],
  ["south korea", "KR"],
  ["australia", "AU"],
  ["russia", "RU"],
  ["brazil", "BR"],
  ["spain", "ES"],
  ["mexico", "MX"],
  ["indonesia", "ID"],
  ["netherlands", "NL"],
  ["switzerland", "CH"],
  ["saudi arabia", "SA"],
  ["turkey", "TR"],
  ["taiwan", "TW"],
  ["poland", "PL"],
  ["sweden", "SE"],
  ["belgium", "BE"],
  ["austria", "AT"],
  ["united arab emirates", "AE"],
  ["norway", "NO"],
  ["iran", "IR"],
  ["nigeria", "NG"],
  ["israel", "IL"],
  ["ireland", "IE"],
  ["hong kong", "HK"],
  ["denmark", "DK"],
  ["singapore", "SG"],
  ["malaysia", "MY"],
  ["philippines", "PH"],
  ["pakistan", "PK"],
  ["finland", "FI"],
  ["south africa", "ZA"],
  ["thailand", "TH"],
  ["colombia", "CO"],
  ["bangladesh", "BD"],
  ["vietnam", "VN"],
  ["egypt", "EG"],
  ["argentina", "AR"],
  ["algeria", "DZ"],
  ["ukraine", "UA"],
  ["chile", "CL"],
  ["iraq", "IQ"],
  ["peru", "PE"],
]);

export const countryCodeToName = new Map([
  ["US", "united states"],
  ["CN", "china"],
  ["JP", "japan"],
  ["DE", "germany"],
  ["GB", "united kingdom"],
  ["IN", "india"],
  ["FR", "france"],
  ["IT", "italy"],
  ["CA", "canada"],
  ["KR", "south korea"],
  ["AU", "australia"],
  ["RU", "russia"],
  ["BR", "brazil"],
  ["ES", "spain"],
  ["MX", "mexico"],
  ["ID", "indonesia"],
  ["NL", "netherlands"],
  ["CH", "switzerland"],
  ["SA", "saudi arabia"],
  ["TR", "turkey"],
  ["TW", "taiwan"],
  ["PL", "poland"],
  ["SE", "sweden"],
  ["BE", "belgium"],
  ["AT", "austria"],
  ["AE", "united arab emirates"],
  ["NO", "norway"],
  ["IR", "iran"],
  ["NG", "nigeria"],
  ["IL", "israel"],
  ["IE", "ireland"],
  ["HK", "hong kong"],
  ["DK", "denmark"],
  ["SG", "singapore"],
  ["MY", "malaysia"],
  ["PH", "philippines"],
  ["PK", "pakistan"],
  ["FI", "finland"],
  ["ZA", "south africa"],
  ["TH", "thailand"],
  ["CO", "colombia"],
  ["BD", "bangladesh"],
  ["VN", "vietnam"],
  ["EG", "egypt"],
  ["AR", "argentina"],
  ["DZ", "algeria"],
  ["UA", "ukraine"],
  ["CL", "chile"],
  ["IQ", "iraq"],
  ["PE", "peru"],
]);

export const countryLabels = [
  { value: "united states", label: "United States" },
  { value: "china", label: "China" },
  { value: "japan", label: "Japan" },
  { value: "germany", label: "Germany" },
  { value: "united kingdom", label: "United Kingdom" },
  { value: "india", label: "India" },
  { value: "france", label: "France" },
  { value: "italy", label: "Italy" },
  { value: "canada", label: "Canada" },
  { value: "south korea", label: "South Korea" },
  { value: "australia", label: "Australia" },
  { value: "russia", label: "Russia" },
  { value: "brazil", label: "Brazil" },
  { value: "spain", label: "Spain" },
  { value: "mexico", label: "Mexico" },
  { value: "indonesia", label: "Indonesia" },
  { value: "netherlands", label: "Netherlands" },
  { value: "switzerland", label: "Switzerland" },
  { value: "saudi arabia", label: "Saudi Arabia" },
  { value: "turkey", label: "Turkey" },
  { value: "taiwan", label: "Taiwan" },
  { value: "poland", label: "Poland" },
  { value: "sweden", label: "Sweden" },
  { value: "belgium", label: "Belgium" },
  { value: "austria", label: "Austria" },
  { value: "united arab emirates", label: "United Arab Emirates" },
  { value: "norway", label: "Norway" },
  { value: "iran", label: "Iran" },
  { value: "nigeria", label: "Nigeria" },
  { value: "israel", label: "Israel" },
  { value: "ireland", label: "Ireland" },
  { value: "hong kong", label: "Hong Kong" },
  { value: "denmark", label: "Denmark" },
  { value: "singapore", label: "Singapore" },
  { value: "malaysia", label: "Malaysia" },
  { value: "philippines", label: "Philippines" },
  { value: "pakistan", label: "Pakistan" },
  { value: "finland", label: "Finland" },
  { value: "south africa", label: "South Africa" },
  { value: "thailand", label: "Thailand" },
  { value: "colombia", label: "Colombia" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "vietnam", label: "Vietnam" },
  { value: "egypt", label: "Egypt" },
  { value: "argentina", label: "Argentina" },
  { value: "algeria", label: "Algeria" },
  { value: "ukraine", label: "Ukraine" },
  { value: "chile", label: "Chile" },
  { value: "iraq", label: "Iraq" },
  { value: "peru", label: "Peru" },
];
