export const countryNameToCode = new Map([
  ["united states", "US"],
  ["china", "CN"],
  ["japan", "JP"],
  ["germany", "DE"],
  ["united kingdom", "GB"],
  ["india", "IN"],
  ["france", "FR"],
  ["italy", "IT"],
  ["canada", "CA"],
  ["south korea", "KR"],
  ["australia", "AU"],
  ["russia", "RU"],
  ["brazil", "BR"],
  ["spain", "ES"],
  ["mexico", "MX"],
  ["indonesia", "ID"],
  ["netherlands", "NL"],
  ["switzerland", "CH"],
  ["saudi arabia", "SA"],
  ["turkey", "TR"],
  ["taiwan", "TW"],
  ["poland", "PL"],
  ["sweden", "SE"],
  ["belgium", "BE"],
  ["austria", "AT"],
  ["united arab emirates", "AE"],
  ["norway", "NO"],
  ["iran", "IR"],
  ["nigeria", "NG"],
  ["israel", "IL"],
  ["ireland", "IE"],
  ["hong kong", "HK"],
  ["denmark", "DK"],
  ["singapore", "SG"],
  ["malaysia", "MY"],
  ["philippines", "PH"],
  ["pakistan", "PK"],
  ["finland", "FI"],
  ["south africa", "ZA"],
  ["thailand", "TH"],
  ["colombia", "CO"],
  ["bangladesh", "BD"],
  ["vietnam", "VN"],
  ["egypt", "EG"],
  ["argentina", "AR"],
  ["algeria", "DZ"],
  ["ukraine", "UA"],
  ["chile", "CL"],
  ["iraq", "IQ"],
  ["peru", "PE"],
]);

export const countryCodeToName = new Map([
  ["US", "united states"],
  ["CN", "china"],
  ["JP", "japan"],
  ["DE", "germany"],
  ["GB", "united kingdom"],
  ["IN", "india"],
  ["FR", "france"],
  ["IT", "italy"],
  ["CA", "canada"],
  ["KR", "south korea"],
  ["AU", "australia"],
  ["RU", "russia"],
  ["BR", "brazil"],
  ["ES", "spain"],
  ["MX", "mexico"],
  ["ID", "indonesia"],
  ["NL", "netherlands"],
  ["CH", "switzerland"],
  ["SA", "saudi arabia"],
  ["TR", "turkey"],
  ["TW", "taiwan"],
  ["PL", "poland"],
  ["SE", "sweden"],
  ["BE", "belgium"],
  ["AT", "austria"],
  ["AE", "united arab emirates"],
  ["NO", "norway"],
  ["IR", "iran"],
  ["NG", "nigeria"],
  ["IL", "israel"],
  ["IE", "ireland"],
  ["HK", "hong kong"],
  ["DK", "denmark"],
  ["SG", "singapore"],
  ["MY", "malaysia"],
  ["PH", "philippines"],
  ["PK", "pakistan"],
  ["FI", "finland"],
  ["ZA", "south africa"],
  ["TH", "thailand"],
  ["CO", "colombia"],
  ["BD", "bangladesh"],
  ["VN", "vietnam"],
  ["EG", "egypt"],
  ["AR", "argentina"],
  ["DZ", "algeria"],
  ["UA", "ukraine"],
  ["CL", "chile"],
  ["IQ", "iraq"],
  ["PE", "peru"],
]);
